services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "9000:9000" 

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/mariadb
      o: bind

networks:
  inception:
    driver: bridge