services:
  mariadb:
    container_name: mariadb
    restart: always
    build: requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - lknetwork

  wordpress:
    container_name: wordpress
    restart: always
    env_file:
      - .env
    build: requirements/wordpress
    volumes:
      - wordpress_data:/var/www/wp/
    networks:
      - lknetwork
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    restart: always
    env_file:
      - .env
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wp/
    networks:
      - lknetwork
    depends_on:
      - wordpress


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress

networks:
  lknetwork:
    name: lknetwork
    driver: bridge
