services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - mynetwork

  wordpress:
    build:
      context: ./requirements/wordpress
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mariadb
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - mynetwork

  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
