FROM nginx:latest

# Copy the HTML file to the NGINX html directory
COPY index.html /usr/share/nginx/html/index.html

# Copy the custom NGINX configuration file
COPY default.conf /etc/nginx/conf.d/default.conf